[package]
name = "traffloat-client"
authors = ["SOFe <sofe2038@gmail.com>"]
version = "0.2.0"
edition = "2018"
repository = "https://github.com/SOF3/traffloat"
homepage = "https://github.com/SOF3/traffloat"
description = "Traffloat web client"
license = "AGPL-3.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.40"
derive-new = "0.5.8"
derive_more = {version = "0.99.13", default-features = false, features = ["index", "index_mut"]}
enum-map = "1.1.0"
getrandom = {version = "0.2.2", features = ["js"]}
getset = "0.1.1"
hex = "0.4.3"
js-sys = "0.3.49"
lazy_static = "1.4.0"
legion = {version = "0.4.0", default-features = false, features = ["codegen"]}
log = "0.4.14"
nalgebra = "0.25.4"
once_cell = "1.7.2"
rand = "0.8.3"
rand_distr = "0.4.0"
rand_xoshiro = "0.6.0"
serde = {version = "1.0.125", features = ["derive"]}
sha2 = "0.9.3"
shrev = "1.1.1"
strum = {version = "0.20.0", features = ["derive"]}
traffloat-codegen = {version = "0.2.0", path = "../codegen-types", features = ["web-sys"]}
traffloat-common = {version = "0.2.0", path = "../common"}
traffloat-safety = {version = "0.2.0", path = "../safety"}
typed-builder = "0.9.0"
wasm-bindgen = {version = "0.2.72"}
wasm-logger = "0.2.0"
yew = {version = "0.18.0", default-features = false, features = ["services", "web_sys"]}

[dependencies.web-sys]
version = "0.3.50"
features = [
	"CanvasGradient",
	"CanvasRenderingContext2d",
	"CssStyleDeclaration",
	"HtmlCanvasElement",
	"HtmlImageElement",
	"ImageBitmap",
	"Performance",
	"Touch",
	"TouchList",
	"WebGlBuffer",
	"WebGlProgram",
	"WebGlRenderingContext",
	"WebGlShader",
	"WebGlTexture",
	"WebGlUniformLocation",
]
