[workspace]
members = ["common", "client", "server", "client/build", "client/model"]

[profile.dev]
opt-level = 3

[profile.dev.package]
traffloat-common = {opt-level = 0}
traffloat-client = {opt-level = 0}
traffloat-server = {opt-level = 0}

[profile.release]
lto = true
opt-level = 3

[profile.release.package.traffloat-client]
opt-level = "s"
