[workspace]
members = [
	"safety",
	"codegen",
	"codegen-types",
	"common",
	# "web",
	"desktop",
]

[profile.dev]
opt-level = 3

[profile.dev.package]
traffloat-common = {opt-level = 0}
# traffloat-web = {opt-level = 0}
traffloat-desktop = {opt-level = 0}

[profile.release]
lto = true
opt-level = 3

# [profile.release.package.traffloat-web]
# opt-level = "s"
