[package]
name = "traffloat-common"
authors = ["SOFe <sofe2038@gmail.com>"]
version = "0.2.0"
edition = "2018"
repository = "https://github.com/SOF3/traffloat"
homepage = "https://github.com/SOF3/traffloat"
description = "Traffloat simulation library"
license = "AGPL-3.0"

[lib]
name = "common"

[dependencies]
nalgebra = "0.24.0"
ratio-def = "0.3.0"
shrev = "1.1.1"
smallvec = "1.6.1"
specs = {version = "0.16.1", default-features = false, features = ["specs-derive"]}
traffloat-codegen = {version = "0.2.0", path = "../codegen"}
yew = {version = "0.17.4", optional = true, default-features = false}
