[package]
name = "traffloat-common"
authors = ["SOFe <sofe2038@gmail.com>"]
version = "0.2.0"
edition = "2018"
repository = "https://github.com/SOF3/traffloat"
homepage = "https://github.com/SOF3/traffloat"
license = "AGPL-3.0"

[lib]
name = "common"

[dependencies]
traffloat-codegen = {version = "0.2.0", path = "../codegen"}
# specs = "0.16.1"
yew = {version = "0.17.4", optional = true}
