[package]
name = "traffloat-common"
authors = ["SOFe <sofe2038@gmail.com>"]
version = "0.2.0"
edition = "2018"
repository = "https://github.com/SOF3/traffloat"
homepage = "https://github.com/SOF3/traffloat"
license = "AGPL-3.0"

[lib]
name = "common"

[dependencies]
derive_more = "0.99.11"
enum-map = "0.6.4"
nalgebra = "0.24.0"
ratio-def = "0.1.2"
specs = {version = "0.16.1", features = ["specs-derive"]}
traffloat-codegen = {version = "0.2.0", path = "../codegen"}
yew = {version = "0.17.4", optional = true}
