name: CI
on:
  - push
  - pull_request
jobs:
  fmt:
    name: rustfmt check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: default
          default: true
          components: rustfmt
      - run: cargo fmt --all -- --check
  lint:
    name: clippy lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
        stability:
          - ""
    steps:
      - uses: actions/checkout@v2
      - run: rm rust-toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          profile: default
          default: true
          components: clippy
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            **/target
          key: ${{ matrix.toolchain }}
      - name: cargo clippy
        run: "cargo clippy --all ${{matrix.stability}}"
  test:
    name: unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
        stability:
          - ""
    steps:
      - uses: actions/checkout@v2
      - run: rm rust-toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          profile: default
          default: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            **/target
          key: ${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
      - name: cargo test
        run: "cargo test --all ${{matrix.stability}}"
