name: Pages
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  site:
    name: "Web client build"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-28
          profile: default
          default: true
      - name: Cache wasm-pack
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
          key: wasm-pack-v0.9
      - run: test -f ~/.cargo/bin/wasm-pack || cargo install wasm-pack

      - name: Install Python dependencies
        run: pip3 install -r client/textures/requirements.txt
      - name: Build Node dependencies
        run: npm install
        working-directory: client
      - name: Build web client
        run: npm run build
        working-directory: client

      - name: Set Git author
        run: git config --global user.name "github-actions[bot]" && git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Setup deploy key
        run: echo ${{secrets.SITE_KEY}} > ${{env.HOME}}/.ssh/id_rsa
      - name: Clone site repo
        run: git clone git@github.com:traffloat/traffloat.github.io ../site
      - name: Delete previous build
        run: test ! -d $(echo ${{github.ref}} | cut -d/ -f3) || rm -r $(echo ${{github.ref}} | cut -d/ -f3)
        working-directory: ../site
      - name: Copy artifact to site repo
        run: cp -r client/dist ../site/$(echo ${{github.ref}} | cut -d/ -f3)
      - name: Git commit
        run: git add $(echo ${{github.ref}} | cut -d/ -f3) && git commit --allow-empty -m "Docs build for traffloat/traffloat@${{github.sha}}"
        working-directory: ../site
      - name: Push pages
        run: git push
        working-directory: ../site

  api:
    name: "Documentation build"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-28
          profile: default
          default: true

      - name: Build documentation
        run: cargo doc --lib

      - name: Set Git author
        run: git config --global user.name "github-actions[bot]" && git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Setup deploy key
        run: echo ${{secrets.API_KEY}} > ${{env.HOME}}/.ssh/id_rsa
      - name: Clone site repo
        run: git clone git@github.com:traffloat/api ../api
      - name: Delete previous build
        run: test ! -d $(echo ${{github.ref}} | cut -d/ -f3) || rm -r $(echo ${{github.ref}} | cut -d/ -f3)
        working-directory: ../api
      - name: Copy artifact to site repo
        run: cp -r client/doc ../api/$(echo ${{github.ref}} | cut -d/ -f3)
      - name: Git commit
        run: git add $(echo ${{github.ref}} | cut -d/ -f3) && git commit --allow-empty -m "Docs build for traffloat/traffloat@${{github.sha}}"
        working-directory: ../api
      - name: Push pages
        run: git push
        working-directory: ../api
