name: Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-28
          profile: default
          default: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
          key: wasm-pack-v0.9
      - run: test -f ~/.cargo/bin/wasm-pack || cargo install wasm-pack
      - name: Check rustc version
        id: rustc-version
        run: echo "::set-ouptut name=RUSTC_VERSION::$(rustc --version)"
      - uses: actions/cache@v2
        with:
          path: |
            **/target
          key: pages-${{ steps.rustc-version.outputs.RUSTC_VERSION }}
      - run: cargo doc --lib
      - run: npm install
        working-directory: client
      - run: npm run build
        working-directory: client
        # - run: cargo build --release
        # working-directory: server
      - run: cp -r client/dist ../pkg
      - run: cp -r target/doc ../pkg/doc
        # - run: cp target/release/traffloat-server ../pkg/server-unix
        # - run: gzip ../pkg/server-unix
      - run: git checkout -- . && git clean -fd
      - run: git fetch && git checkout gh-pages
      - run: test ! -d $(echo ${{github.ref}} | cut -d/ -f3) || rm -r $(echo ${{github.ref}} | cut -d/ -f3)
      - run: cp -r ../pkg $(echo ${{github.ref}} | cut -d/ -f3)
      - run: git config --local user.name "github-actions[bot]" && git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git add $(echo ${{github.ref}} | cut -d/ -f3) && git commit --allow-empty -m "Docs build for SOF3/traffloat@${{github.sha}}"
      - run: git push
