name: Guide build
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    name: "Guide build"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-28
          profile: default
          default: true
      - name: Cache cargo tools
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
          key: just
      - run: test -f ~/.cargo/bin/just || cargo install just

      - name: Install toolchain dependencies
        run: just deps
      - name: Install mkdocs
        run: pip3 install mkdocs-material
      - name: Preprocess resources
        run: just pp
      - name: Build documentation
        run: just guide

      - name: Set Git author
        run: git config --global user.name "github-actions[bot]" && git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Clone site repo
        uses: actions/checkout@v2
        with:
          repository: traffloat/guide
          ssh-key: ${{secrets.GUIDE_KEY}}
          path: .site-repo
      - name: Delete previous build
        run: test ! -d $(echo ${{github.ref}} | cut -d/ -f3) || rm -r $(echo ${{github.ref}} | cut -d/ -f3)
        working-directory: .site-repo
      - name: Copy artifact to site repo
        run: cp -r docgen/output/site .site-repo/$(echo ${{github.ref}} | cut -d/ -f3)
      - name: Git commit
        run: git add $(echo ${{github.ref}} | cut -d/ -f3) && git commit --allow-empty -m "Docs build for traffloat/traffloat@${{github.sha}}"
        working-directory: .site-repo
      - name: Push pages
        run: git push
        working-directory: .site-repo
