[package]
name = "traffloat-desktop"
authors = ["SOFe <sofe2038@gmail.com>"]
version = "0.2.0"
edition = "2018"
repository = "https://github.com/SOF3/traffloat"
homepage = "https://github.com/SOF3/traffloat"
description = "Traffloat desktop client"
license = "AGPL-3.0"

[dependencies]
anyhow = "1.0.40"
legion = {version = "0.4.0", default-features = false, features = ["codegen"]}
log = "0.4.14"
nalgebra = "0.27.1"
serde = {version = "1.0.125", features = ["derive"]}
shrev = "1.1.1"
strum = {version = "0.21.0", features = ["derive"]}
traffloat-codegen = {version = "0.2.0", path = "../codegen-types", features = ["web-sys"]}
traffloat-common = {version = "0.2.0", path = "../common"}
traffloat-safety = {version = "0.2.0", path = "../safety"}
typed-builder = "0.9.0"
